#!/bin/bash
if [[ -z ~/bin/$1 ]]; then updated="Added"; else updated="Updated"; fi;
echo 'EDITOR=',$EDITOR
if [[ ! $EDITOR ]]; then EDITOR=mcedit; fi;
$EDITOR ~/bin/"$1"
chmod ugo+x ~/bin/"$1"
cd ~/bin
git add "$1"
git commit "$1" -m "$updated command '$1'"
#fi
