#!/bin/bash
LSCOLOR="--color"
if [[ `uname` == 'Darwin' ]]; then LSCOLOR="-G"; fi
ROOT='/var'
if [[ `ls /Projects/ 2>/dev/null` ]]; then ROOT="/Projects"; fi
PROJECT=$1
if [[ ! $1 ]]; then
    ls -AH $LSCOLOR -d $ROOT/*/*/ $ROOT/*/
else
    CHOICES=`ls -d $ROOT/$1/ $ROOT/*/$1/ 2>/dev/null | head -n 1`
    echo "Directory is now $CHOICES"
    cd $CHOICES
    ls $LSCOLOR -ApH
fi
