#!/bin/bash
ROOT='/var'
if [[ `ls /Projects/` ]]; then ROOT="/Projects"; fi
PROJECT=$1
if [[ ! $1 ]]; then
    ls -ApGH -d $ROOT/*/* | grep "/$" | cut -d "/" -f 3-
else
    CHOICES=`ls -d $ROOT/$1 $ROOT/*/$1 2>/dev/null | head -n 1`
    echo "Directory is now $CHOICES"
    cd $CHOICES
    ls -ApGH
fi
