#!/bin/bash
cmd=shift;
stdout=$1.stdout.log
stderr=$1.stderr.log
$2 %* 1>$stdout 2>$stderr
if [[ ! -z $stderr ]]; then
    echo "Cronrun finished with an exception!"
    echo "Errors:"
    cat $stderr
    echo "Output:"
    cat $stdout
elif [[ `grep $stdout "Traceback.*most recent call last $stdout"` ]]; then 
    echo "Crashed on cronrun:"
    cat $stdout
fi;
