#!/bin/bash
#Bash command to run django batch scripts.
#I put it into my ~/bin/ directory under name "django" and call as simple "django script.py arg1".
#Expects that settings.py file is located in the project root dir.

function raise {
    if [[ $TERM ]]; then
        tput setaf 1; tput bold; echo $2; tput sgr0; exit $1;
    else
	echo $2; exit $1;
    fi;
}

#echo "$@" >> ~/bin/django.log

if ! [[ $1 ]]; then raise 1 "Usage: django [-u] script.py [arg1] [arg2] ..."; fi;

script=$1
if [[ $1 == "-u" ]]; then script=$2; fi;

# run standard module
if [[ $script =~ "/PySrc/interpreterInfo.py" ]]; then # hack for pydev interpreters
    cat "$1" | sed "s#import sys#import sys; sys.executable='$0'#" | cat > /tmp/django-pydev.py
    python -u "/tmp/django-pydev.py"
fi;

if ! [[ -f $script ]]; then raise 2 "File '$script' not found"; fi;

DIR=`dirname $script`;
DIR=`pwd $DIR`;
cd $DIR

SETTINGS=$DIR;
while ! [[ -f "$SETTINGS/settings.py" ]]; do
    if [[ $SETTINGS == "/" || $SETTINGS == "" ]]; then
        SETTINGS="";
        break;
    fi; 
    SETTINGS=`dirname $SETTINGS`;
done;

if ! [[ $SETTINGS ]]; then raise 3 "No settings.py found! Can't set pythonpath! Exiting."; fi;
export DJANGO_SETTINGS_MODULE=settings
export PYTHONPATH=$SETTINGS

python "$@"
