#!/bin/sh
i=0;
declare -a args
while [[ "z$1" == z-* ]]; do
    args[$i]=$1;
    i=$(expr $i + 1);
    args[$i]=$2;
    i=$(expr $i + 1);
    shift 2;
done;
find . "${args[@]}" -print0 | xargs -0 -n 1 echo
