#!/bin/sh

# A better syntax for find
#
#   each -name "*.pyc" -do rm 
# will be translated to:
#   find . -name "*.pyc" -print0 | xargs -0 -n 1 rm
# or that also often can be written as
#   find . -name "*.pyc" -exec rm {} \;
#
# and
#   each -name "*.pyc" -run cd {}; git gc; cd ..;
# will be translated to:
#   find . -name "*.pyc" -print0 | xargs -0 -n 1 -J {} (cd {}; git gc; cd ..)

i=0;
while [[ "z$1" != "z-do" && "z$1" != "z-run" && "$1" != "" ]]; do
    args[$i]=$1;
    i=$(expr $i + 1);
    shift;
done;
if [ "$1" == "-do" ] ; then
    shift; # skip this -do
    find . "${args[@]}" -print0 | xargs -0 -n 1 "$@"
elif [ "$1" == "-run" ] ; then
    shift; # skip this -run
    $AFS='\0';
    for $i in `find . "${args[@]}" -print0`; do $@; done;
else;
    find . "${args[@]}" -print0
fi;
